# Test against this version of Node.js
environment:
  nodejs_version: "6.3.1"

before_build:
  - nuget restore

cache :
  - packages -> **\packages.config
  - library-grad-project\client\node_modules -> library-grad-project\client\package.json

# Install scripts. (runs after repo cloning)
install:

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Go to node project directory
  - cd library-grad-project\client
  # install modules
  - npm install
  - cd ..\..\

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - cd library-grad-project-tests\bin\Debug
  - '%xunit20%\xunit.console.x86 library-grad-project-tests.dll -appveyor'
  - cd ..\..\..\library-grad-project\client
  - npm test

build:
 verbosity : minimal
