export const REQUEST_BOOKS = 'REQUEST_BOOKS';
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';

export const REQUEST_RESERVATIONS = 'REQUEST_RESERVATIONS';
export const RECEIVE_RESERVATIONS = 'RECEIVE_RESERVATIONS';
